### ISSUE TITLE
Ambiguous nature of ID

### ISSUE THREAD

**Issue by marksbrown** [dpapathanasiou/simple-graph#14]
Id's are numerical in the tests which JSONDecoder is happy with despite the unnecessary need to decode the IDs as JSON. 

If you create a key as a string for instance this will work but will not be possible to decode as the json library in python expects strings to be explicitly quoted. Thus you cannot traverse or visualise if edges aren't double quoted strings.

Should I be double quoting my strings for IDs?

I'll post a coded example later on if this isn't clear

**Comment by marksbrown** [comment]
https://gist.github.com/marksbrown/0514b90a78b9eb6a845f9d2b96d0a69c

**Comment by marksbrown** [comment]
It's probably due to my own ignorance of sqlite / JSON but I'm not sure what the correct thing to do is with regards to creating 'good IDs'.

**Comment by dpapathanasiou** [comment]
Hi @marksbrown and thank you for pointing this out

There is nothing wrong with strings as id values; instead, the problem is here in [_unpack_edge](https://github.com/dpapathanasiou/simple-graph/blob/main/python/database.py#L241-L242), which is localized in the [visualize](https://github.com/dpapathanasiou/simple-graph/blob/main/python/database.py#L237) function:

```python
    def _unpack_edge(edge):
        return [json.loads(item) for item in edge]
```

That logic assumes that the three columns returned by querying the `edges` table are all in json format.

I'll correct this and update the tests accordingly.

In the meantime, if you change the above to this, you'll find it works as expected, regardless of the type of id used:

```python
     def _unpack_edge(edge):
        src, tgt, props = edge
        return [src, tgt, json.loads(props)]
 ```

**Comment by marksbrown** [comment]
Thanks for getting back to me so quickly!
