### ISSUE TITLE
Searching for nodes where query must match a value in an array in the body

### ISSUE THREAD

**Issue by rajarshi** [dpapathanasiou/simple-graph#17]
I'm looking to do something like this

```
from simple_graph_sqlite import database as db 
dbfile = "db.sqlite"

db.initialize(dbfile)

db.atomic(dbfile, db.add_node({'name': 'foo', 'type':['company', 'start-up']}, 1))
db.atomic(dbfile, db.add_node({'name': 'bar', 'type':['cat', 'apple']}, 1))

db.atomic(apple, db.find_nodes({'type': 'apple'}, db._search_like, db._search_starts_with))
```
But I don't think the last statement works

**Comment by dpapathanasiou** [comment]
Hi @rajarshi

You're right, the current search statements do not introspect the json object correctly; looking at the [sqlite json docs](https://www.sqlite.org/json1.html), it seems that statement need to use `json_each.value LIKE ...` or `json_tree.type IN ...` instead.

I can tinker with this some more, to see how to introduce those; ideally, I'd like to include them as statements in the [sql](https://github.com/dpapathanasiou/simple-graph/tree/main/sql) so they're usable by any programming language that supports sql bindings, rather than coming up with a python-specific solution.

**Comment by rajarshi** [comment]
Got it, thanks

**Comment by dpapathanasiou** [comment]
Hi @rajarshi 

I've recently revamped the search functions for allow for this; see the [test](https://github.com/dpapathanasiou/simple-graph/blob/main/python/database_test.py#L103) and the [updated example](https://github.com/dpapathanasiou/simple-graph/tree/main/python#example) for how it works now, using the search templates.
